/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model_Obj2(props) {
  const { nodes, materials } = useGLTF('/Room.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Room.geometry} material={nodes.Room.material} position={[0, 0.41, 0]} scale={4} />
      <mesh geometry={nodes.Sofa.geometry} material={nodes.Sofa.material} position={[-0.06, 0.61, 2.42]} rotation={[Math.PI, 0, Math.PI]} scale={[3.16, 1, 1]}>
        <mesh geometry={nodes.Circle.geometry} material={nodes.Circle.material} scale={[0.32, 1, 1]} />
        <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[-0.44, 0.67, 0.17]} scale={[0.44, 1.06, 0.81]} />
        <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[0.44, 0.67, 0.17]} scale={[0.44, 1.06, 0.81]} />
        <mesh geometry={nodes.Plane004_1.geometry} material={nodes.Plane004_1.material} position={[0.61, 1.73, -0.63]} rotation={[Math.PI / 2, 0, 0]} scale={[0.31, 1, 0.48]} />
        <mesh geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[0, 1.73, -0.63]} rotation={[Math.PI / 2, 0, 0]} scale={[0.31, 1, 0.48]} />
        <mesh geometry={nodes.Plane006_1.geometry} material={nodes.Plane006_1.material} position={[-0.61, 1.73, -0.63]} rotation={[Math.PI / 2, 0, 0]} scale={[0.31, 1, 0.48]} />
        <mesh geometry={nodes.Plane007_1.geometry} material={nodes.Plane007_1.material} position={[0.61, 1.73, -0.63]} rotation={[Math.PI / 2, 0, 0]} scale={[0.31, 1, 0.48]} />
        <mesh geometry={nodes.Plane008.geometry} material={nodes.Plane008.material} position={[0.9, 1.26, 0.35]} rotation={[-1.56, 1.54, 1.53]} scale={[0.6, 0.62, 0.09]} />
        <mesh geometry={nodes.Plane009.geometry} material={nodes.Plane009.material} position={[-0.9, 1.26, 0.35]} rotation={[1.56, 1.54, -1.53]} scale={[0.6, 0.62, 0.09]} />
      </mesh>
      <mesh geometry={nodes.Television.geometry} material={nodes.Television.material} position={[-0.28, 3.63, -3.88]} rotation={[Math.PI / 2, 0, 0]} scale={[1.97, 1.12, 1.12]} />
      <mesh geometry={nodes.Tv_Cabinet.geometry} material={nodes.Tv_Cabinet.material} position={[0.03, 0.41, -3.36]} scale={[1, 1.08, 1.08]}>
        <mesh geometry={nodes.Plane012_4.geometry} material={nodes.Plane012_4.material} position={[-0.03, 0, 0]} />
      </mesh>
      <mesh geometry={nodes.Book.geometry} material={nodes.Book.material} position={[2.12, 1.24, -3.01]} rotation={[Math.PI, -0.87, Math.PI]} scale={[0.19, 0.18, 0.24]} />
      <mesh geometry={nodes.Book4.geometry} material={nodes.Book4.material} position={[-1.83, 0.6, -2.99]} scale={[0.19, 0.08, 0.24]} />
      <mesh geometry={nodes.Book6.geometry} material={nodes.Book6.material} position={[2.4, 0.82, -2.99]} rotation={[Math.PI / 2, 0, 1.4]} scale={[0.19, 0.14, 0.22]} />
      <mesh geometry={nodes.Book9.geometry} material={nodes.Book9.material} position={[-1.62, 1.9, 1.89]} rotation={[0.06, -1.15, 0.04]} scale={[0.17, 0.08, 0.19]} />
      <mesh geometry={nodes.Book2.geometry} material={nodes.Book2.material} position={[2.75, 0.84, -2.99]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.19, 0.19, 0.24]} />
      <mesh geometry={nodes.Book5.geometry} material={nodes.Book5.material} position={[-1.38, 0.69, -3.12]} rotation={[0.98, 1.14, -0.93]} scale={[0.19, 0.12, 0.23]} />
      <mesh geometry={nodes.Book3.geometry} material={nodes.Book3.material} position={[-1.84, 0.66, -3.13]} rotation={[0, -1.05, 0]} scale={[0.19, 0.19, 0.24]} />
      <mesh geometry={nodes.Book8.geometry} material={nodes.Book8.material} position={[2.07, 0.61, -3.05]} rotation={[0, -1.15, 0]} scale={[0.17, 0.08, 0.19]} />
      <mesh geometry={nodes.Book7.geometry} material={nodes.Book7.material} position={[2.57, 0.83, -2.99]} rotation={[Math.PI / 2, -0.26, Math.PI / 2]} scale={[0.19, 0.12, 0.24]} />
      <mesh geometry={nodes.Coffee.geometry} material={nodes.Coffee.material} position={[-0.75, 1.4, -0.45]} rotation={[Math.PI / 2, 0, 2.44]} scale={0.07}>
        <mesh geometry={nodes.water.geometry} material={nodes.water.material} position={[0.15, -0.96, -0.04]} rotation={[Math.PI / 2, 0.7, Math.PI]} scale={15.3} />
      </mesh>
      <mesh geometry={nodes.Dvd_Player.geometry} material={nodes.Dvd_Player.material} position={[-0.06, 0.57, -3.27]} rotation={[Math.PI, 0, Math.PI]} scale={[0.08, 0.06, 0.09]}>
        <mesh geometry={nodes.Arch35_050_001.geometry} material={nodes.Arch35_050_001.material} />
        <mesh geometry={nodes.Arch35_051_001.geometry} material={nodes.Arch35_051_001.material} />
        <mesh geometry={nodes.Arch35_052_001.geometry} material={nodes.Arch35_052_001.material} />
        <mesh geometry={nodes.Arch35_053_001.geometry} material={nodes.Arch35_053_001.material} />
        <mesh geometry={nodes.Arch35_054_001.geometry} material={nodes.Arch35_054_001.material} />
        <mesh geometry={nodes.Arch35_056_001.geometry} material={nodes.Arch35_056_001.material} />
        <mesh geometry={nodes.Arch35_057_001.geometry} material={nodes.Arch35_057_001.material} />
        <mesh geometry={nodes.Arch35_058_001.geometry} material={nodes.Arch35_058_001.material} />
      </mesh>
      <mesh geometry={nodes.Guitar.geometry} material={nodes.Guitar.material} position={[-3.79, 1.82, -3.63]} rotation={[2.87, -0.88, -1.71]} scale={0.07} />
      <mesh geometry={nodes.Indoor_Plant.geometry} material={nodes.Indoor_Plant.material} position={[3.42, 0.41, -3.36]} rotation={[0, Math.PI / 2, 0]} scale={0}>
        <mesh geometry={nodes.Dirt.geometry} material={nodes.Dirt.material} position={[-93.2, 0.04, 46.98]} />
        <mesh geometry={nodes.Dirt02.geometry} material={nodes.Dirt02.material} position={[0, 354.44, 0]} />
        <mesh geometry={nodes.Leaf000.geometry} material={nodes.Leaf000.material} position={[15.85, 1016.6, 288.26]} />
        <mesh geometry={nodes.Leaf008.geometry} material={nodes.Leaf008.material} position={[192.18, 619.19, 48.51]} />
        <mesh geometry={nodes.Leaf009.geometry} material={nodes.Leaf009.material} position={[-208.45, 596.19, -44.55]} />
        <mesh geometry={nodes.Leaf010.geometry} material={nodes.Leaf010.material} position={[-91.63, 511.38, 95.45]} />
        <mesh geometry={nodes.Leaf011.geometry} material={nodes.Leaf011.material} position={[-29.97, 649.38, -231.33]} />
        <mesh geometry={nodes.Leaf006000.geometry} material={nodes.Leaf006000.material} position={[15.2, 1038.56, -352.58]} />
        <mesh geometry={nodes.Leaf007.geometry} material={nodes.Leaf007.material} position={[347.83, 736.29, -262.99]} />
        <mesh geometry={nodes.leaf02000.geometry} material={nodes.leaf02000.material} position={[-34.45, 1280.3, 2.76]} />
        <mesh geometry={nodes.leaf03000.geometry} material={nodes.leaf03000.material} position={[367.88, 1072.77, -54.79]} />
        <mesh geometry={nodes.leaf05000.geometry} material={nodes.leaf05000.material} position={[-351.01, 870.81, 251.12]} />
        <mesh geometry={nodes.lef04000.geometry} material={nodes.lef04000.material} position={[-462.61, 934.73, -232.39]} />
        <mesh geometry={nodes.Moh.geometry} material={nodes.Moh.material} position={[-6.77, -65.68, 2]} />
        <mesh geometry={nodes.stem.geometry} material={nodes.stem.material} position={[-9.67, 271.9, -13.49]} />
      </mesh>
      <mesh geometry={nodes.Phone.geometry} material={nodes.Phone.material} position={[0.28, 1.29, -0.16]} rotation={[0, -0.17, Math.PI]} scale={0}>
        <mesh geometry={nodes.Cap1.geometry} material={nodes.Cap1.material} />
        <mesh geometry={nodes.Cap1_1.geometry} material={nodes.Cap1_1.material} />
        <mesh geometry={nodes.Cap1_2.geometry} material={nodes.Cap1_2.material} />
        <mesh geometry={nodes.Cap1_3.geometry} material={nodes.Cap1_3.material} />
        <mesh geometry={nodes.Cap1_4.geometry} material={nodes.Cap1_4.material} />
        <mesh geometry={nodes.Cap1_5.geometry} material={nodes.Cap1_5.material} />
        <mesh geometry={nodes.Cap1_6.geometry} material={nodes.Cap1_6.material} />
        <mesh geometry={nodes.Cap2.geometry} material={nodes.Cap2.material} />
        <mesh geometry={nodes.Cap2_1.geometry} material={nodes.Cap2_1.material} />
        <mesh geometry={nodes.Cap2_2.geometry} material={nodes.Cap2_2.material} />
        <mesh geometry={nodes.Cap2_3.geometry} material={nodes.Cap2_3.material} />
        <mesh geometry={nodes.Cap2_4.geometry} material={nodes.Cap2_4.material} />
        <mesh geometry={nodes.Cap2_5.geometry} material={nodes.Cap2_5.material} />
        <mesh geometry={nodes.Cap2_6.geometry} material={nodes.Cap2_6.material} />
        <mesh geometry={nodes.Capsule.geometry} material={nodes.Capsule.material} />
        <mesh geometry={nodes.Capsule1.geometry} material={nodes.Capsule1.material} />
        <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} />
        <mesh geometry={nodes.Cube1.geometry} material={nodes.Cube1.material} />
        <mesh geometry={nodes.Extrude.geometry} material={nodes.Extrude.material} />
        <mesh geometry={nodes.Extrude1.geometry} material={nodes.Extrude1.material} />
        <mesh geometry={nodes.Extrude2.geometry} material={nodes.Extrude2.material} />
        <mesh geometry={nodes.Extrude_2.geometry} material={nodes.Extrude_2.material} />
      </mesh>
      <mesh geometry={nodes.Remote.geometry} material={nodes.Remote.material} position={[0.82, 1.22, -3.34]} rotation={[0, Math.PI / 9, 0]} scale={0.06} />
      <mesh geometry={nodes.Soundbar.geometry} material={nodes.Soundbar.material} position={[-0.59, 1.72, -3.86]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.09, 2.87, 0.16]}>
        <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[0.15, 0.02, 0]} scale={[0.96, 0.91, 0.96]} />
        <mesh geometry={nodes.Plane022.geometry} material={nodes.Plane022.material} position={[0.56, -0.9, 0.31]} scale={[10.57, 0.27, 6.22]} />
        <mesh geometry={nodes.SketchUp001.geometry} material={nodes.SketchUp001.material} position={[1.48, -0.55, 0.04]} rotation={[0, 0, -Math.PI / 2]} scale={[0, 0.01, 0.01]} />
        <mesh geometry={nodes.SketchUp002.geometry} material={nodes.SketchUp002.material} position={[1.48, 0.13, -0.23]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[0, 0.01, 0.01]} />
        <mesh geometry={nodes.SketchUp005.geometry} material={nodes.SketchUp005.material} position={[1.48, -0.69, 0.04]} rotation={[0, 0, -Math.PI / 2]} scale={[0, 0.01, 0.01]} />
        <mesh geometry={nodes.SketchUp006.geometry} material={nodes.SketchUp006.material} position={[1.48, 0.39, 0.04]} rotation={[0, 0, -Math.PI / 2]} scale={[0, 0.01, 0.01]} />
        <mesh geometry={nodes.SketchUp003.geometry} material={nodes.SketchUp003.material} position={[1.47, 0.1, 0.03]} rotation={[0, 0, -Math.PI / 2]} scale={[0, 0, 0.01]} />
        <mesh geometry={nodes.SketchUp004.geometry} material={nodes.SketchUp004.material} position={[1.47, -0.43, 0.03]} rotation={[0, 0, -Math.PI / 2]} scale={[0, 0, 0.01]} />
      </mesh>
      <mesh geometry={nodes.Tea_Table.geometry} material={nodes.Tea_Table.material} position={[0.07, 0.41, -1.08]} rotation={[Math.PI / 2, 0, 0.61]} scale={2.44} />
      <mesh geometry={nodes.Wall_Frame.geometry} material={nodes.Wall_Frame.material} position={[-4, 3.47, -0.76]} rotation={[1.57, 0, -Math.PI / 2]} scale={[3.06, 3.53, 3.53]} />
      <mesh geometry={nodes.PS4_Controller.geometry} material={nodes.PS4_Controller.material} position={[-0.09, 1.4, -0.37]} rotation={[-0.26, 0.25, 0.07]} scale={0.5} />
      <mesh geometry={nodes.PS4_Controller001.geometry} material={nodes.PS4_Controller001.material} position={[-0.68, 0.54, -0.4]} rotation={[-2.88, 0.25, 3.08]} scale={0.5} />
      <mesh geometry={nodes.PS4_Top.geometry} material={nodes.PS4_Top.material} position={[-0.05, 1.29, -3.34]} scale={0.37}>
        <mesh geometry={nodes.PS4_Base.geometry} material={nodes.PS4_Base.material} position={[0, -0.11, 0.04]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Room.gltf')
