/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Akshaykhedkar97 (https://sketchfab.com/Akshaykhedkar97)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bathroom-interior-7609ef43ffc04cc280f1525ffdc6d89a
title: Bathroom Interior
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene (props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  const meshData = [
    {position: [-1.94, 0.39, 0.84], rotation: [0, -Math.PI / 2, 0], scale: 0.27, geometry: nodes.Object_4.geometry, material: materials.ceramic_objects},
    {position: [-0.62, 0, -0.6], rotation: [0, 0, 0], scale: 1, geometry: nodes.Object_6.geometry, material: materials.ceiling},
    {position: [2.47, 1.69, 1.69], rotation: [-Math.PI, 0, -Math.PI], scale: [-1.23, 1.23, 1.23], geometry: nodes.Object_8.geometry, material: materials.lamp_cloth},
    {position: [2.47, 1.69, 1.69], rotation: [-Math.PI, 0, -Math.PI], scale: [-1.23, 1.23, 1.23], geometry: nodes.Object_10.geometry, material: materials.lamp_metal},
    {position: [-1.47, 2.9, -1.08], rotation: [0, 0, 0], scale: 1, geometry: nodes.Object_12.geometry, material: materials.bathroomceiling},
    {position: [-0.62, 0, -0.6], rotation: [0, 0, 0], scale: 1, geometry: nodes.Object_14.geometry, material: materials.bathroom_wall},
    {position: [0.25, 1.2, -1.36], rotation: [-Math.PI / 2, 0, 0], scale: [-0.05, 0.05, 0.05], geometry: nodes.Object_60.geometry, material: materials.artisticwall},
    {position: [-0.62, 0, -0.6], rotation: [0, 0, 0], scale: 1, geometry: nodes.Object_62.geometry, material: materials.vanitywall},
    {position: [0.62, 1.26, -0.16], rotation: [0, 0, 0], scale: 0.78, geometry: nodes.Object_58.geometry, material: materials.floor},
  ]



  {/*<group position={[0.62, 1.26, -0.16]} scale={0.78}>*/}
  {/*  <mesh geometry={nodes.Object_58.geometry} material={materials.floor} />*/}
  {/*</group>*/}
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          {
            meshData.map((el, index) =>(
              <group position={el.position} rotation={el.rotation} scale={el.scale}>
                <mesh
                  onClick={() => props.setSelectedItemIndex(index)} geometry={el.geometry}
                  material={ props.items && props.items[index].isBought ? el.material : null}>
                  { props.items && !props.items[index].isBought ? <meshBasicMaterial wireframe={props.items && !props.items[index].isBought}   color="#2125294f" /> : null}
                </mesh>
              </group>
            ))
          }

          {/*<group position={[-1.47, 2.9, -1.08]}>*/}
          {/*  <mesh geometry={nodes.Object_16.geometry} material={materials.shower_light} />*/}
          {/*</group>*/}
          {/*<group position={[-1.47, 2.9, -1.08]}>*/}
          {/*  <mesh geometry={nodes.Object_18.geometry} material={materials.showerpanel} />*/}
          {/*</group>*/}
          {/*<group position={[-2.35, 0.75, 0.88]}>*/}
          {/*  <mesh geometry={nodes.Object_20.geometry} material={materials.jetspray} />*/}
          {/*</group>*/}
          {/*<group position={[-1.17, 1.18, -1.88]} rotation={[0, Math.PI / 2, 0]}>*/}
          {/*  <mesh geometry={nodes.Object_22.geometry} material={materials.crome} />*/}
          {/*</group>*/}
          {/*<group position={[0.6, 0.66, -1.09]} scale={0.07}>*/}
          {/*  <mesh geometry={nodes.Object_24.geometry} material={materials.faucethandle} />*/}
          {/*</group>*/}
          {/*<group position={[2.1, 0.27, 1.66]} scale={[0.47, 0.91, 0.47]}>*/}
          {/*  <mesh geometry={nodes.Object_26.geometry} material={materials.dustbin} />*/}
          {/*</group>*/}
          {/*<group position={[-2.26, 0.28, 0.43]} rotation={[Math.PI / 2, 0, 0]} scale={[0.14, 0.2, 0.14]}>*/}
          {/*  <mesh geometry={nodes.Object_28.geometry} material={materials.toiletpaper} />*/}
          {/*</group>*/}
          {/*<group position={[-1.47, 2.9, -0.51]} scale={0.09}>*/}
          {/*  <mesh geometry={nodes.Object_30.geometry} material={materials.bathroom_light} />*/}
          {/*</group>*/}
          {/*<group position={[-1.25, 2.9, 0.93]} scale={0.22}>*/}
          {/*  <mesh geometry={nodes.Object_32.geometry} material={materials.passage_light} />*/}
          {/*</group>*/}
          {/*<group position={[-2.43, 1.55, 0.98]} scale={0.72}>*/}
          {/*  <mesh geometry={nodes.Object_34.geometry} material={materials.window} />*/}
          {/*</group>*/}
          {/*<group position={[2.47, 1.85, 0.9]}>*/}
          {/*  <mesh geometry={nodes.Object_36.geometry} material={materials.mirror_body} />*/}
          {/*</group>*/}
          {/*<group position={[2.47, 1.85, 0.9]}>*/}
          {/*  <mesh geometry={nodes.Object_38.geometry} material={materials.mirror_glass} />*/}
          {/*</group>*/}
          {/*<group position={[-1.52, 1.25, -0.89]}>*/}
          {/*  <mesh geometry={nodes.Object_40.geometry} material={materials.encloserglass} />*/}
          {/*</group>*/}
          {/*<group position={[-1.47, 1.42, -0.15]}>*/}
          {/*  <mesh geometry={nodes.Object_42.geometry} material={materials.senclosure} />*/}
          {/*</group>*/}
          {/*<group position={[1.01, 0.78, -1.23]} rotation={[0, -0.8, 0]} scale={0.01}>*/}
          {/*  <mesh geometry={nodes.Object_44.geometry} material={materials.towel01} />*/}
          {/*</group>*/}
          {/*<group position={[2.12, 0.25, 0.66]} rotation={[-Math.PI, 0.06, -Math.PI]} scale={0.03}>*/}
          {/*  <mesh geometry={nodes.Object_46.geometry} material={materials.handwash} />*/}
          {/*</group>*/}
          {/*<group position={[1.66, 2.46, -0.98]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.59}>*/}
          {/*  <mesh geometry={nodes.Object_48.geometry} material={materials.decoreplate} />*/}
          {/*</group>*/}
          {/*<group position={[1.01, 0.78, -1.23]} rotation={[0, -0.8, 0]} scale={0.01}>*/}
          {/*  <mesh geometry={nodes.Object_50.geometry} material={materials.towel02} />*/}
          {/*</group>*/}
          {/*<group position={[-1.77, 1.3, -1.95]} rotation={[Math.PI / 2, 0, 0]} scale={0.15}>*/}
          {/*  <mesh geometry={nodes.Object_52.geometry} material={materials.shower_head} />*/}
          {/*</group>*/}
          {/*<group position={[-0.29, 0.76, -1.15]} rotation={[0, 1.56, 0]} scale={0.26}>*/}
          {/*  <mesh geometry={nodes.Object_54.geometry} material={materials.flowerpot} />*/}
          {/*</group>*/}
          {/*<group position={[2.33, 0.97, 1.65]} rotation={[Math.PI / 2, 0, 1.11]} scale={0}>*/}
          {/*  <mesh geometry={nodes.Object_56.geometry} material={materials.plant} />*/}
          {/*</group>*/}

          {/*<group position={[0.25, 1.2, -1.36]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.05, 0.05, 0.05]}>*/}
          {/*  <mesh geometry={nodes.Object_60.geometry} material={materials.artisticwall} />*/}
          {/*</group>*/}
          {/*<group position={[-0.62, 0, -0.6]}>*/}
          {/*  <mesh geometry={nodes.Object_62.geometry} material={materials.vanitywall} />*/}
          {/*</group>*/}
          {/*<group position={[2.21, 0.43, 0.91]} rotation={[-Math.PI, 0, -Math.PI]}>*/}
          {/*  <mesh geometry={nodes.Object_64.geometry} material={materials.vanitycounter} />*/}
          {/*</group>*/}
          {/*<group position={[-0.62, 0, -0.6]}>*/}
          {/*  <mesh geometry={nodes.Object_66.geometry} material={materials.sidewall} />*/}
          {/*</group>*/}
          {/*<group position={[2.24, 0.93, -0.01]} rotation={[-0.65, 0.09, 1.64]} scale={1.41}>*/}
          {/*  <mesh geometry={nodes.Object_68.geometry} material={materials.towelroll} />*/}
          {/*</group>*/}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
